#!/usr/bin/env python3
import tomllib
import json
from pathlib import Path

repo_dir = Path(__file__).parent.parent
pyproject_file = repo_dir / "pyproject.toml"
pyproject = tomllib.loads(pyproject_file.read_text())

manifest_file = repo_dir / "custom_components/gridboss/manifest.json"
manifest = json.loads(manifest_file.read_text())

manifest["version"] = pyproject["project"]["version"]
def ignore_dep(dep: str) -> bool:
    return dep.startswith("homeassistant")

manifest["dependencies"] = [
    dep for dep in pyproject["project"]["dependencies"]
    if not ignore_dep(dep)
]

manifest_file.write_text(json.dumps(manifest, indent=2) + "\n")
