name: 'Lint'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Run ruff
        run: uv run --frozen ruff check .
